services:

  # ember-feature-extraction-pipeline:
  #   image: ghcr.io/w-disaster/ember:master
  #   container_name: ember-feature-extraction-pipeline
  #   environment:
  #     MALWARE_DIR_PATH: /usr/input_data/malware/
  #     FINAL_DATASET_DIR: /usr/app/dataset/
  #     N_PROCESSES: 32
  #   volumes:
  #     - "/home/luca/WD/NortonDataset670/MALWARE/:/usr/input_data/malware/"
  #     - "./raw_dataset/:/usr/app/dataset/"

  # ember-train-test-split:
  #   image: prova
  #   container_name: ember-train-test-split
  #   environment:
  #     RAW_DATASET_PATH: "/usr/app/raw_dataset/"
  #     BASE_OUTPUT_PATH: "/usr/app/splitted_dataset/"
  #   volumes:
  #     - "./raw_dataset/:/usr/app/raw_dataset/"
  #     - "./splitted_dataset/:/usr/app/splitted_dataset/"

  transcendent-pipeline:
    image: transcendent #ghcr.io/w-disaster/transcendent-multiclass:main
    container_name: transcendent-pipeline
    environment:
      BASE_DATASET_PATH: /usr/app/dataset/
      PE_DATASET_TYPE: "ember" # e.g. "motif", "ember", "dts"
      TRAIN_TEST_SPLIT_TYPE: "time_split" # e.g. "random_split", "time_split"

    volumes:
      - "./results/:/usr/app/models/"
      - "./splitted_dataset/:/usr/app/dataset/"

    